services:
  back:
    build: ./back
    container_name: lockbox_back
    env_file:
      - ./back/.env
    ports:
      - "8080:8080"
    restart: on-failure:3
    networks:
      - app
    command: ["--seed"]
networks:
  app: