server:
  port: 8080

security:
  token:
    issuer: ${TOKEN_ISSUER}
    secret: ${TOKEN_SECRET}
    duration: ${TOKEN_DURATION}

spring:
  application:
    name: LockBox API
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:lockbox
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect