server:
  port: 8080

security:
  token:
    issuer: ${TOKEN_ISSUER}
    secret: ${TOKEN_SECRET}
    duration: ${TOKEN_DURATION}

spring:
  application:
    name: LockBox API
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    locations: classpath:db/migration
    ignore-migration-patterns: '*:missing'